name: CI/CD workflow

on: 
  push:
  pull_request:
    branches:
        main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: test workflow
        run: echo "It works!"
      # - uses: actions/checkout@v2
      # - uses: actions/setup-node@v2
      #   with:
      #       node-version: '16.14.0'
        
      # - name: "Install dependencies"
      #   run: npm install
    
      # - name: "Compile project"
      #   run: npx hardhat compile
    
      # - name: "Run hardhat tests"
      #   run: npx hardhat test test/