name: CI/CD workflow
on: 
  push:
    branches: '*'
  pull_request:
    branches:
        main
    types:
        closed

jobs:
  build-and-test:
    runs-on: Ubuntu 20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
            node-version: '16.14.0'
        
      - name: "Install dependencies"
        run: npm install
    
      - name: "Compile project"
        run: npx hardhat compile
    
      - name: "Run hardhat tests"
        run: npx hardhat test test/