name: CI/CD workflow

on: 
  push:
  pull_request:
    branches:
        main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: contract

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20.11.1'
        
      - name: "Install dependencies"
        run: npm install
    
      - name: "Compile project"
        run: npx hardhat compile
    
      - name: "Run hardhat tests"
        run: npx hardhat test

  run-static-analyis:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10' 

      - name: "Install slither"
        run: python3 -m pip install slither-analyzer

      - name: "Run static analysis"
        run: | 
          cd contract/contracts
          slither .

      
  deploy-to-mumbai:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: contract
        
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20.11.1'
            
      - name: "Install dependencies"
        run: npm install

      - name: "Deploy to mumbai testnet"
        run: npx hardhat ignition deploy ignition/modules/NFTTracker.js --network mumbai