name: CI/CD workflow

on: 
    push:
        branches: [main]


jobs:
    build-and-test:
        runs-on: linux-latest
    
    steps:
    - name: Checkout code
    uses: actions/checkout@v2

    - name: Setup Node
    uses: actions/setup-node@v2
    with:
        node-version: '16.14.0'
           
    - name: Install dependencies
    run: npm install
       
    - name: Compile project
    run: npx hardhat compile
    - name: Run hardhat tests
    run: npx hardhat test test/

